services:
  suscriptions.api:
    image: ${DOCKER_REGISTRY-}suscriptionsapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        ConnectionStrings__AppDb: ${SUSCRIPTIONS_DB_CONNECTIONSTRING}
        AccessTokenSettings__publicKey: ${AUTH_RSA_PUBLICKEY}
        AccessTokenSettings__Issuer: http://localhost:5000
        AccessTokenSettings__Audience: http://localhost:6001
    ports:
      - "${SUSCRIPTIONS_PORT}:8080"
    networks:
      - app-suscriptions
  
networks:
    app-suscriptions:
